#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frpc[-1]
	add ucitrack frpc
	set ucitrack.@frpc[-1].init=frpc
	commit ucitrack
EOF

common=$(uci -q get frpc.@common[-1])

if [ -z "$common" ]; then
  uci -q add frpc common
fi

if [ ."$common" != ."main" ]; then
  uci -q batch <<-EOF >/dev/null
		rename frpc.@common[-1]="main"
		set frpc.main.enabled="0"
		commit frpc
	EOF
fi

rm -f /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
